service: sls-workshop

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  s3event:
    handler: handler.s3event
    events:
      - s3: shimokitaoss-${opt:stage}
